# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
require:
  - rubocop-performance
  - rubocop-rspec
AllCops:
  TargetRubyVersion: 3.3.0
  SuggestExtensions: false
  NewCops: enable

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec

Metrics/MethodLength:
  Max: 25
  Exclude:
  - 'spec/**/*'

Metrics/BlockLength:
  Max: 25
  Exclude:
  - 'spec/**/*'

Metrics/ClassLength:
  Max: 100
  Exclude:
  - 'spec/**/*'
  - 'lib/retf/decoder.rb'

Metrics/CyclomaticComplexity:
  Exclude:
  - 'spec/**/*'
  - 'lib/retf/decoder.rb'

Metrics/AbcSize:
  Exclude:
  - 'spec/**/*'
  - 'lib/retf/decoder.rb'

RSpec/ExampleLength:
  Max: 50

RSpec/SpecFilePathFormat:
  Enabled: false
